### ISSUE TITLE
Image doesn't run

### ISSUE THREAD

**Issue by TedAvery** [marcelmaatkamp/docker-alpine-radius-home#1]
Without any modification, this image doesn't seem to run at all for me. I go straight to the docker build and docker run commands from the readme, but the container immediately exits. Strangley, docker logs doesn't show anything at all.

I also tried running the base image of marcelmaatkamp/freeradius, but same problem. Any ideas? Should this currently be working?

**Comment by marcelmaatkamp** [comment]
"Sun May 24 07:43:29 2015 : Error: libssl version mismatch.  built: 1000201f linked: 100010cf"

It seems the libssl version is upgraded in alpine/edge, will fix asap, thanks for bringing it up!

**Comment by marcelmaatkamp** [comment]
It seems freeradius3 became the default standard, image is modified accordingly.
